USE [SUCOS_VENDAS]
GO
/****** Object:  Table [dbo].[TABELA DE CLIENTES]    Script Date: 2021-08-30 8:59:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABELA DE CLIENTES](
	[CPF] [varchar](11) NOT NULL,
	[NOME] [varchar](100) NULL,
	[ENDERECO1] [varchar](150) NULL,
	[ENDERECO2] [varchar](150) NULL,
	[BAIRRO] [varchar](50) NULL,
	[CIDADE] [varchar](50) NULL,
	[ESTADO] [varchar](2) NULL,
	[CEP] [varchar](8) NULL,
	[DATA DE NASCIMENTO] [date] NULL,
	[IDADE] [smallint] NULL,
	[SEXO] [varchar](1) NULL,
	[LIMITE DE CREDITO] [money] NULL,
	[VOLUME DE COMPRA] [float] NULL,
	[PRIMEIRA COMPRA] [bit] NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABELA DE PRODUTOS]    Script Date: 2021-08-30 8:59:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABELA DE PRODUTOS](
	[CODIGO DO PRODUTO] [varchar](10) NOT NULL,
	[NOME DO PRODUTO] [varchar](50) NULL,
	[EMBALAGEM] [varchar](20) NULL,
	[TAMANHO] [varchar](10) NULL,
	[SABOR] [varchar](20) NULL,
	[PRECO DE LISTA] [smallmoney] NOT NULL,
 CONSTRAINT [PK_TABELA DE PRODUTOS] PRIMARY KEY CLUSTERED 
(
	[CODIGO DO PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABELA DE VENDEDORES]    Script Date: 2021-08-30 8:59:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABELA DE VENDEDORES](
	[MATRICULA] [varchar](10) NOT NULL,
	[NOME] [varchar](100) NULL,
	[PERCENTUAL COMISSÃO] [real] NOT NULL,
 CONSTRAINT [PK_TABELA_DE_VENDEDORES] PRIMARY KEY CLUSTERED 
(
	[MATRICULA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'1471156710', N'Érica Carvalho', N'R. Iriquitia', N'', N'Jardins', N'São Paulo', N'SP', N'80012212', CAST(N'1990-09-01' AS Date), 27, N'F', 170000.0000, 245000, 0)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'19290992743', N'Fernando Cavalcante', N'R. Dois de Fevereiro', N'', N'Água Santa', N'Rio de Janeiro', N'RJ', N'22000000', CAST(N'2000-02-12' AS Date), 18, N'M', 100000.0000, 200000, 1)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'2600586709', N'César Teixeira', N'Rua Conde de Bonfim', N'', N'Tijuca', N'Rio de Janeiro', N'RJ', N'22020001', CAST(N'2000-03-12' AS Date), 18, N'M', 120000.0000, 220000, 0)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'3623344710', N'Marcos Nougeuira', N'Av. Pastor Martin Luther King Junior', N'', N'Inhauma', N'Rio de Janeiro', N'RJ', N'22002012', CAST(N'1995-01-13' AS Date), 23, N'M', 110000.0000, 220000, 1)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'492472718', N'Eduardo Jorge', N'R. Volta Grande', N'', N'Tijuca', N'Rio de Janeiro', N'RJ', N'22012002', CAST(N'1994-07-19' AS Date), 23, N'M', 75000.0000, 95000, 1)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'50534475787', N'Abel Silva ', N'Rua Humaitá', N'', N'Humaitá', N'Rio de Janeiro', N'RJ', N'22000212', CAST(N'1995-09-11' AS Date), 22, N'M', 170000.0000, 260000, 0)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'5576228758', N'Petra Oliveira', N'R. Benício de Abreu', N'', N'Lapa', N'São Paulo', N'SP', N'88192029', CAST(N'1995-11-14' AS Date), 22, N'F', 70000.0000, 160000, 1)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'5648641702', N'Paulo César Mattos', N'Rua Hélio Beltrão', N'', N'Tijuca', N'Rio de Janeiro', N'RJ', N'21002020', CAST(N'1991-08-30' AS Date), 26, N'M', 120000.0000, 220000, 0)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'5840119709', N'Gabriel Araujo', N'R. Manuel de Oliveira', N'', N'Santo Amaro', N'São Paulo', N'SP', N'80010221', CAST(N'1985-03-16' AS Date), 32, N'M', 140000.0000, 210000, 1)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'7771579779', N'Marcelo Mattos', N'R. Eduardo Luís Lopes', N'', N'Brás', N'São Paulo', N'SP', N'88202912', CAST(N'1992-03-25' AS Date), 25, N'M', 120000.0000, 200000, 1)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'8502682733', N'Valdeci da Silva', N'R. Srg. Édison de Oliveira', N'', N'Jardins', N'São Paulo', N'SP', N'82122020', CAST(N'1995-10-07' AS Date), 22, N'M', 110000.0000, 190000, 0)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'8719655770', N'Carlos Eduardo', N'Av. Gen. Guedes da Fontoura', N'', N'Jardins', N'São Paulo', N'SP', N'81192002', CAST(N'1983-12-20' AS Date), 34, N'M', 200000.0000, 240000, 0)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'9283760794', N'Edson Meilelles', N'R. Pinto de Azevedo', N'', N'Cidade Nova', N'Rio de Janeiro', N'RJ', N'22002002', CAST(N'1995-10-07' AS Date), 22, N'M', 150000.0000, 250000, 1)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'94387575700', N'Walber Lontra', N'R. Cel. Almeida', N'', N'Piedade', N'Rio de Janeiro', N'RJ', N'22000201', CAST(N'1989-06-20' AS Date), 28, N'M', 60000.0000, 120000, 1)
GO
INSERT [dbo].[TABELA DE CLIENTES] ([CPF], [NOME], [ENDERECO1], [ENDERECO2], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], [IDADE], [SEXO], [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA]) VALUES (N'95939180787', N'Fábio Carvalho', N'R. dos Jacarandás da Península', N'', N'Barra da Tijuca', N'Rio de Janeiro', N'RJ', N'22002020', CAST(N'1992-01-05' AS Date), 16, N'M', 90000.0000, 180000, 1)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1000889', N'Sabor da Montanha - 700 ml - Uva', N'Garrafa', N'700 ml', N'Uva', 6.3090)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1002334', N'Linha Citros - 1 Litro - Lima/Limão', N'PET', N'1 Litro', N'Lima/Limão', 7.0040)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1002767', N'Videira do Campo - 700 ml - Cereja/Maça', N'Garrafa', N'700 ml', N'Cereja/Maça', 8.4100)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1004327', N'Videira do Campo - 1,5 Litros - Melância', N'PET', N'1,5 Litros', N'Melância', 19.5100)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1013793', N'Videira do Campo - 2 Litros - Cereja/Maça', N'PET', N'2 Litros', N'Cereja/Maça', 24.0100)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1022450', N'Festival de Sabores - 2 Litros - Açai', N'PET', N'2 Litros', N'Açai', 38.0120)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1037797', N'Clean - 2 Litros - Laranja', N'PET', N'2 Litros', N'Laranja', 16.0080)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1040107', N'Light - 350 ml - Melância', N'Lata', N'350 ml', N'Melância', 4.5550)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1041119', N'Linha Citros - 700 ml - Lima/Limão', N'Garrafa', N'700 ml', N'Lima/Limão', 4.9040)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1042712', N'Linha Citros - 700 ml - Limão', N'Garrafa', N'700 ml', N'Limão', 4.9040)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1051518', N'Frescor do Verão - 470 ml - Limão', N'Garrafa', N'470 ml', N'Limão', 3.2995)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1078680', N'Frescor do Verão - 470 ml - Manga', N'Garrafa', N'470 ml', N'Manga', 5.1795)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1086543', N'Linha Refrescante - 1 Litro - Manga', N'PET', N'1 Litro', N'Manga', 11.0105)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1088126', N'Linha Citros - 1 Litro - Limão', N'PET', N'1 Litro', N'Limão', 7.0040)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1096818', N'Linha Refrescante - 700 ml - Manga', N'Garrafa', N'700 ml', N'Manga', 7.7105)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'1101035', N'Linha Refrescante - 1 Litro - Morango/Limão', N'PET', N'1 Litro', N'Morango/Limão', 9.0105)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'229900', N'Pedaços de Frutas - 350 ml - Maça', N'Lata', N'350 ml', N'Maça', 4.2110)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'231776', N'Festival de Sabores - 700 ml - Açai', N'Garrafa', N'700 ml', N'Açai', 13.3120)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'235653', N'Frescor do Verão - 350 ml - Manga', N'Lata', N'350 ml', N'Manga', 3.8595)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'243083', N'Festival de Sabores - 1,5 Litros - Maracujá', N'PET', N'1,5 Litros', N'Maracujá', 10.5120)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'290478', N'Videira do Campo - 350 ml - Melância', N'Lata', N'350 ml', N'Melância', 4.5600)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'326779', N'Linha Refrescante - 1,5 Litros - Manga', N'PET', N'1,5 Litros', N'Manga', 16.5105)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'394479', N'Sabor da Montanha - 700 ml - Cereja', N'Garrafa', N'700 ml', N'Cereja', 8.4090)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'479745', N'Clean - 470 ml - Laranja', N'Garrafa', N'470 ml', N'Laranja', 3.7680)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'520380', N'Pedaços de Frutas - 1 Litro - Maça', N'PET', N'1 Litro', N'Maça', 12.0110)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'544931', N'Frescor do Verão - 350 ml - Limão', N'Lata', N'350 ml', N'Limão', 2.4595)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'695594', N'Festival de Sabores - 1,5 Litros - Açai', N'PET', N'1,5 Litros', N'Açai', 28.5120)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'723457', N'Festival de Sabores - 700 ml - Maracujá', N'Garrafa', N'700 ml', N'Maracujá', 4.9120)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'746596', N'Light - 1,5 Litros - Melância', N'PET', N'1,5 Litros', N'Melância', 19.5050)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'773912', N'Clean - 1 Litro - Laranja', N'PET', N'1 Litro', N'Laranja', 8.0080)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'783663', N'Sabor da Montanha - 700 ml - Morango', N'Garrafa', N'700 ml', N'Morango', 7.7090)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'788975', N'Pedaços de Frutas - 1,5 Litros - Maça', N'PET', N'1,5 Litros', N'Maça', 18.0110)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'812829', N'Clean - 350 ml - Laranja', N'Lata', N'350 ml', N'Laranja', 2.8080)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'826490', N'Linha Refrescante - 700 ml - Morango/Limão', N'Garrafa', N'700 ml', N'Morango/Limão', 6.3105)
GO
INSERT [dbo].[TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA]) VALUES (N'838819', N'Clean - 1,5 Litros - Laranja', N'PET', N'1,5 Litros', N'Laranja', 12.0080)
GO
INSERT [dbo].[TABELA DE VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO]) VALUES (N'00236', N'Claudia Mariella da Silva', 0.08)
GO
INSERT [dbo].[TABELA DE VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO]) VALUES (N'00239', N'Alberto de Sá Verneck', 0.117128007)
GO
INSERT [dbo].[TABELA DE VENDEDORES] ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO]) VALUES (N'00241', N'Albertino de Sá Verneck', 0.08)
GO
